### ISSUE TITLE
Handle null values with spec in parent

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/lynx-parser#8]
The following document will fail parsing because the image value is null. I believe this is a valid document.
```
spec:
  hints: ["container"]
  children: [ { name: "image", hints: ["image", "content"] } ]
value:
  image: null
```
